cmdb/urls.py
from django.conf.urls import include, url

from cmdb.views import *

urlpatterns = [
    # 机房等级

    url(r'^idc_level_list/', include([
        url(r'^delete_entity/', IDCLevelDeleteView.as_view(), name='idc_level_delete'),
        url(r'^(?P<pk>\d+)/idc_level_edit/', IDCLevelUpdateView.as_view(), name='idc_level_edit'),
        url(r'^idc_level_add/', IDCLevelCreateView.as_view(), name='idc_level_add'),
        url(r'^$', IDCLevelView.as_view(), name='idc_level_list'),
    ])),

    # ISP
    url(r'^isp_list/', include([
        url(r'^delete_entity/', ISPDeleteView.as_view(), name='isp_delete'),
        url(r'^(?P<pk>\d+)/isp_edit/', ISPUpdateView.as_view(), name='isp_edit'),
        url(r'^isp_add/', ISPCreateView.as_view(), name='isp_add'),
        url(r'^$', ISPView.as_view(), name='isp_list'),
    ])),

    # IDC
    url(r'^idc_list/', include([
        url(r'^delete_entity/', IDCDeleteView.as_view(), name='idc_delete'),
        url(r'^(?P<pk>\d+)/idc_edit/', IDCUpdateView.as_view(), name='idc_edit'),
        url(r'^idc_add/', IDCCreateView.as_view(), name='idc_add'),
        url(r'^$', IDCView.as_view(), name='idc_list'),
    ])),

    # 机柜
    url(r'^cabinet_list/', include([
        url(r'^delete_entity/', CabinetDeleteView.as_view(), name='cabinet_delete'),
        url(r'^(?P<pk>\d+)/cabinet_edit/', CabinetUpdateView.as_view(), name='cabinet_edit'),
        url(r'^cabinet_add/', CabinetCreateView.as_view(), name='cabinet_add'),
        url(r'^$', CabinetView.as_view(), name='cabinet_list'),
    ])),

    # 机架
    url('^rack_list/', include([
        url(r'^load_cabinet_list/', LoadCabinetListView.as_view()),
        url(r'^load_rack_list/', LoadRackListView.as_view()),
        url(r'^delete_entity/', RackDeleteView.as_view(), name='rack_delete'),
        url(r'^(?P<pk>\d+)/rack_edit/', RackUpdateView.as_view(), name='rack_edit'),
        url(r'^rack_add/', RackCreateView.as_view(), name='rack_add'),
        url(r'^$', RackView.as_view(), name='rack_list'),
    ])),

    # 主机组
    url('^hostgroup_list/', include([
        url(r'^delete_entity/', HostGroupDeleteView.as_view(), name='hostgroup_delete'),
        url(r'^(?P<pk>\d+)/hostgroup_edit/', HostGroupUpdateView.as_view(), name='hostgroup_edit'),
        url(r'^hostgroup_add/', HostGroupCreateView.as_view(), name='hostgroup_add'),
        url(r'^$', HostGroupView.as_view(), name='hostgroup_list'),
    ])),

    # 主机
    url('^host_list/', include([
        url(r'scan_host_job/', ScanHostJobView.as_view()),
        url(r'^delete_entity/', HostDeleteView.as_view(), name='host_delete'),
        url(r'^(?P<pk>\d+)/host_edit/', HostUpdateView.as_view(), name='host_edit'),
        url(r'^host_add/', HostCreateView.as_view(), name='host_add'),
        url(r'^host_export/', HostExportView, name='host_export'),
        url(r'^$', HostView.as_view(), name='host_list'),
    ])),

    # 资产导入
    url(r'assert_import/', include([
        url(r'upload_file/', AssertImportView.as_view()),
        url(r'^$', AssertImportCreateView.as_view(), name='assert_import'),
    ])),

]

deploy_manager/urls.py
from django.conf.urls import include, url

# from deploy_manager.rest.project_version_rest import ProjectVersionUpdateRest
from deploy_manager.rest.project_version_rest import ProjectVersionUpdateRest
from deploy_manager.views import *

urlpatterns = [
    # 业务模块
    url(r'^project_module_list/', include([
        url(r'^delete_entity/', ProjectModuleDeleteView.as_view(), name='project_module_delete'),
        url(r'^(?P<pk>\d+)/project_module_edit/', ProjectModuleUpdateView.as_view(), name='project_module_edit'),
        url(r'^project_module_add/', ProjectModuleCreateView.as_view(), name='project_module_add'),
        url(r'^$', ProjectModuleView.as_view(), name='project_module_list'),
    ])),

    # 业务
    url(r'^project_list/', include([
        url(r'^project_deploy_history/', ProjectDeployHistoryView.as_view()),
        url(r'^delete_entity/', ProjectDeleteView.as_view(), name='project_delete'),
        url(r'^(?P<pk>\d+)/project_edit/', ProjectUpdateView.as_view(), name='project_edit'),
        url(r'^project_add/', ProjectCreateView.as_view(), name='project_add'),
        url(r'^project_version/', ProjectVersionCreateView.as_view()),
        url(r'^(?P<pk>\d+)/project_version_edit/', ProjectVersionUpdateView.as_view()),
        url(r'delete_project_version/', ProjectVersionDeleteView.as_view()),
        url(r'project_deploy_action/', ProjectDeployActionView.as_view()),
        url(r'project_host_deploy_action/',
            ProjectHostDeployActionView.as_view()),
        url(r'project_deploy/', ProjectDeployView.as_view()),
        url(
            r'^(?P<username>\w+)/(?P<password>\w+)/(?P<project_name>\w+)/(?P<project_version_name>\w+)/project_version_update_rest/',
            ProjectVersionUpdateRest),
        url(r'^$', ProjectView.as_view(), name='project_list'),
    ]))
]

saltops/urls.py
# -*- coding: utf-8 -*-
"""saltops URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions import serializers
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from rest_framework import routers

# from deploy_manager.serializer import UserViewSet
from common import views
from common.views import LoginView
from deploy_manager.views import *
from saltops import settings

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^app/', TemplateView.as_view(template_name="index.html")),
    url(r'^api/', include('base_auth.api_urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', LoginView.as_view(), name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^mainform/$', views.mainform, name='mainform'),
    url(r'^dashboard/$', views.dashboard, name='mainform'),
    url(r'^frontend/cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^frontend/tools_manager/', include('tools_manager.urls', namespace='tools_manager')),
    url(r'^frontend/deploy_manager/', include('deploy_manager.urls', namespace='deploy_manager')),
    url(r'^frontend/base_auth/', include('base_auth.urls', namespace='base_auth')),
    url(r'^frontend/celery_manager/', include('celery_manager.urls', namespace='celery_manager'))
]
#
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]
admin.site.site_header = 'SaltOps'
admin.site.site_title = 'SaltOps'

deploy_manager/models/DeployJob.py
from django.db import models
from common.models import BaseModel
from deploy_manager.models.ProjectVersion import ProjectVersion

DEPLOY_STATUS = (
    (0, '部署中'),
    (1, '部署完成'),
    (2, '部署失败'),
    (3, '启动中'),
    (4, '启动成功'),
    (5, '启动失败'),
    (6, '卸载中'),
    (7, '卸载成功'),
    (8, '卸载失败'),
    (9, '暂停中'),
    (10, '暂停成功'),
    (11, '暂停失败'),
)


class DeployJob(BaseModel):
    project_version = models.ForeignKey(ProjectVersion, verbose_name='版本')
    job_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="作业名称")
    deploy_status = models.IntegerField(null=True, blank=True, verbose_name="部署状态", choices=DEPLOY_STATUS,
                                        default=0)

    def __str__(self):
        return self.job_name

    class Meta:
        verbose_name = "历史作业"
        verbose_name_plural = verbose_name

deploy_manager/models/DeployJobDetail.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel
from deploy_manager.models.DeployJob import DeployJob


class DeployJobDetail(BaseModel):
    host = models.ForeignKey(Host, verbose_name='主机名')
    deploy_message = models.TextField(verbose_name='作业信息', blank=True, null=True)
    job = models.ForeignKey(DeployJob, verbose_name='作业名称', blank=True, null=True)

    job_cmd = models.TextField(blank=True, null=True, verbose_name="作业命令")
    start_time = models.DateTimeField(verbose_name='开始时间', blank=True, null=True)
    duration = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='执行时长', blank=True, null=True)
    stderr = models.TextField(blank=True, null=True, verbose_name="其他信息")
    comment = models.TextField(blank=True, null=True, verbose_name="提示信息", default="")
    is_success = models.BooleanField(choices=((True, '执行成功'), (False, '执行失败')), verbose_name='执行情况', default=True)

    def __str__(self):
        return ""

    class Meta:
        verbose_name = "部署详情"
        verbose_name_plural = verbose_name

deploy_manager/models/Project.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from libsaas.services.basecamp.projects import Project

from cmdb.models import Host
from common.models import BaseModel
from deploy_manager.models.ProjectModule import ProjectModule
from saltops.settings import SALT_OPS_CONFIG

JOB_SCRIPT_TYPE = (
    (100, '----'),
    (0, 'sls'),
    (1, 'shell'),
)


class Project(BaseModel):
    name = models.CharField(max_length=255, blank=True, null=True, verbose_name="业务名称")
    project_module = models.ForeignKey(ProjectModule, verbose_name='业务模块', blank=True, null=True, default="")
    dev_monitor = models.ForeignKey(User, verbose_name='开发负责人', blank=True, null=True, related_name='dev_monitor')
    ops_monitor = models.ForeignKey(User, verbose_name='运维负责人', blank=True, null=True, related_name='ops_monitor')
    backup_monitor = models.ForeignKey(User, verbose_name='备份负责人', blank=True, null=True, related_name='backup_monitor')
    # template_sls = models.FileField(verbose_name='SLS模板包', blank=True, null=True,
    #                                 upload_to=SALT_OPS_CONFIG['package_path'],
    #                                 validators=[FileExtensionValidator(['zip'])])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "业务"
        verbose_name_plural = verbose_name

deploy_manager/models/ProjectConfigFile.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel
from deploy_manager.models import *


class ProjectConfigFile(BaseModel):
    project = models.ForeignKey(Project, verbose_name='业务', null=True)
    config_path = models.CharField(max_length=255, verbose_name='配置文件路径', blank=True, null=True)

    def __str__(self):
        return self.config_path

    class Meta:
        verbose_name = "业务配置"
        verbose_name_plural = verbose_name

deploy_manager/models/ProjectHost.py
from django.db import models
from cmdb.models import Host
from common.models import BaseModel
from deploy_manager.models.Project import Project

DEPLOY_STATUS = (
    (0, '未部署'),
    (1, '部署成功'),
    (2, '部署失败'),
    (3, '启动成功'),
    (4, '启动失败'),
    (5, '暂停成功'),
    (6, '暂停失败'),
    (7, '卸载成功'),
    (8, '卸载失败'),
)


class ProjectHost(BaseModel):
    host = models.ForeignKey(Host, verbose_name='主机')
    project = models.ForeignKey(Project, verbose_name='业务')
    is_running = models.BooleanField(null=False, blank=False, default=False, verbose_name='是否运行')
    project_version_id = models.TextField(default="", blank=True, null=True, verbose_name='已部署版本的ID')
    deploy_states = models.IntegerField(verbose_name='部署状态', choices=(DEPLOY_STATUS), default=0)

    def __str__(self):
        return self.host.host_name

    class Meta:
        verbose_name = "业务主机"
        verbose_name_plural = verbose_name

deploy_manager/models/ProjectVersion.py
from django.db import models
from common.models import BaseModel
from common.storages import OverwriteStorage
from deploy_manager.models.Project import Project, JOB_SCRIPT_TYPE
from django.core.validators import FileExtensionValidator

from saltops.settings import SALT_OPS_CONFIG


class ProjectVersion(BaseModel):
    project = models.ForeignKey(Project, default="", verbose_name="业务名称", blank=True, null=True, )
    files = models.FileField(verbose_name='SLS包', blank=True, null=True,
                             upload_to=SALT_OPS_CONFIG['package_path'],
                             validators=[FileExtensionValidator(['zip'])])
    software_files = models.FileField(verbose_name='应用包', blank=True, null=True,
                                      upload_to=SALT_OPS_CONFIG['package_path'])

    def __str__(self):
        return self.project.__str__() + '---' + self.files

    class Meta:
        verbose_name = "版本信息"
        verbose_name_plural = verbose_name

deploy_manager/forms/ProjectForm.py
from django import forms

from common.constants import FORM_WIDGET_BASE_STYLE
from deploy_manager.models import ProjectModule, Project, ProjectVersion


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'


class ProjectListFilterForm(forms.Form):
    name = forms.CharField(required=False, label='业务名称')


class ProjectVersionForm(forms.ModelForm):
    class Meta:
        model = ProjectVersion
        fields = ['project', 'files', 'software_files']

deploy_manager/forms/ProjectModuleForm.py
from django import forms

from common.constants import FORM_WIDGET_BASE_STYLE
from deploy_manager.models import ProjectModule, Project, ProjectVersion


class ProjectModuleForm(forms.ModelForm):
    class Meta:
        model = ProjectModule
        fields = '__all__'


class ProjectModuleListFilterForm(forms.Form):
    parent = forms.ModelChoiceField(
        required=False,
        queryset=ProjectModule.objects,
        empty_label='上级业务')

deploy_manager/views.py
from django.shortcuts import render
from rest_framework import viewsets

from deploy_manager.models import *
from deploy_manager.serializers import *


class ProjectVersionViewSet(viewsets.ModelViewSet):
    queryset = ProjectVersion.objects.all()
    serializer_class = ProjectVersionSerializer


class ProjectViewSet(viewsets.ModelViewSet):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer


class DeployJobViewSet(viewsets.ModelViewSet):
    queryset = DeployJob.objects.all()
    serializer_class = DeployJobSerializer

deploy_manager/views/project_module.py
from braces.views import *
from django.contrib.auth.mixins import *
from django.urls import *
from django.views.generic import *

from deploy_manager.forms import ProjectModuleForm, ProjectModuleListFilterForm
from deploy_manager.models import *
from saltops.settings import PER_PAGE

listview_lazy_url = 'deploy_manager:project_module_list'
listview_template = 'deploy_manager/project_module_list.html'
formview_template = 'deploy_manager/project_module_form.html'


class ProjectModuleView(LoginRequiredMixin, OrderableListMixin, ListView):
    model = ProjectModule
    paginate_by = PER_PAGE
    template_name = listview_template
    context_object_name = 'result_list'
    orderable_columns_default = 'id'
    orderable_columns = ['name', 'parent', 'create_time', 'update_time']

    def get_queryset(self):
        result_list = ProjectModule.objects.all()
        parent = self.request.GET.get('parent')
        order_by = self.request.GET.get('order_by')
        ordering = self.request.GET.get('ordering')
        if order_by:
            if ordering == 'desc':
                result_list = result_list.order_by('-' + order_by)
            else:
                result_list = result_list.order_by(order_by)
        if parent:
            result_list = result_list.filter(parent=parent)
        return result_list

    def get_context_data(self, **kwargs):
        context = super(ProjectModuleView, self).get_context_data(**kwargs)
        context['order_by'] = self.request.GET.get('order_by', '')
        context['ordering'] = self.request.GET.get('ordering', 'asc')
        context['filter_form'] = ProjectModuleListFilterForm(self.request.GET)
        return context


class ProjectModuleCreateView(LoginRequiredMixin, CreateView):
    model = ProjectModule
    form_class = ProjectModuleForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class ProjectModuleUpdateView(LoginRequiredMixin, UpdateView):
    model = ProjectModule
    form_class = ProjectModuleForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class ProjectModuleDeleteView(LoginRequiredMixin, JSONResponseMixin,
                              AjaxResponseMixin, View):
    def get_ajax(self, request, *args, **kwargs):
        ids = request.GET.get('id', '')
        if ids != "":
            ProjectModule.objects.filter(pk__in=map(int, ids.split(','))).delete()
            return self.render_json_response({"success": True})
        else:
            return self.render_json_response({"success": False})

deploy_manager/templates/deploy_manager/project_deploy_history.html
{% extends 'common/basic_layout.html' %}

{% block content %}
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>执行记录</h5>
                <a class=" pull-right" href="javascript:history.go(-1)">返回</a>
            </div>

            <div class="ibox-content timeline">
                {% for o in result_list %}
                    <div class="timeline-item">
                        <div class="row">
                            <div class="col-xs-4 date">
                                <i class="fa fa-briefcase"></i> {{ o.create_time }}
                                <br>
                                <small class="text-navy">{{ o.human_time }}</small>
                            </div>
                            <div class="col-xs-7 content no-top-border">
                                <p>作业名称: {{ o.result_hist.0.job }}</p>
                                <p>目标主机: {{ o.result_hist.0.host }}</p>
                                <a href="javascript:void(0)" onclick="showHistory('{{ o.id }}')">详细信息</a>
                                <div id="{{ o.id }}" style="display: none">
                                    {% for v in o.result_hist %}

                                        <p>
                                            作业命令: {{ v.job_cmd|replace_to_br }}
                                        </p>
                                        <p>
                                            作业信息: {{ v.deploy_message|replace_to_br }}
                                        </p>
                                        <p>执行时长: {{ v.duration }}毫秒</p>
                                        <p>其他信息: {{ v.stderr|replace_to_br }}</p>
                                        <p>提示信息: {{ v.comment|replace_to_br }}</p>
                                        <p>
                                            执行情况:
                                            {% if v.is_success %}执行成功
                                            {% else %}执行失败
                                            {% endif %}
                                        </p>
                                        <hr/>
                                    {% endfor %}
                                </div>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="hr-line-dashed"></div>
            {% include 'common/pagination.html' %}
        </div>
    </div>
    <script>
        function showHistory(id) {
            $('#' + id).toggle()
        }
    </script>
{% endblock %}

deploy_manager/templates/deploy_manager/project_module_form.html
{% extends 'common/basic_form.html' %}
{% block titleblock %}
    业务模块
{% endblock %}

deploy_manager/templates/deploy_manager/project_version_edit_form.html
{% extends 'common/basic_layout.html' %}

{% block content %}
    <script src="/static/asserts/require.js"></script>
    <link href="/static/hplus/css/plugins/chosen/chosen.css" rel="stylesheet">
    <script src="/static/hplus/js/plugins/chosen/chosen.jquery.js"></script>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>版本编辑
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <form method="post" enctype="multipart/form-data"
                              onsubmit="return preSubmit()"
                              class="form-horizontal">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.files.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.files }}
                                    {{ form.files.errors }}
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-primary" type="submit">保存</button>
                                    <a class="btn btn-white" href="javascript:history.go(-1)">取消</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        var install_script_editor;
        var anti_install_script_editor;
        var extra_param_editor;
        var stateguard_script_editor;
        var start_script_editor;
        var stop_script_editor;
        var state_script_editor;
        function preSubmit() {
            debugger;
            $('#id_install_script').val(install_script_editor.getValue())
            $('#id_anti_install_script').val(anti_install_script_editor.getValue())
            $('#id_extra_param').val(extra_param_editor.getValue())
            $('#id_stateguard_script').val(stateguard_script_editor.getValue())
            $('#id_start_script').val(start_script_editor.getValue())
            $('#id_stop_script').val(stop_script_editor.getValue())
            $('#id_state_script').val(state_script_editor.getValue())
            return true;
        }
        $(document).ready(function () {
            var fieldObj = $('.form-horizontal input')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
            fieldObj = $('.form-horizontal textarea')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }

            fieldObj = $('.form-horizontal select')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
            $('#id_is_default').removeClass('form-control')
            $('#id_files').removeClass('form-control')
            $('#files-clear_id').removeClass('form-control')


        })
        require.config({paths: {ace: "/static/asserts/ace/lib/ace"}})

        define('editor', ['ace/ace'],
            function (ace, langtools) {
                install_script_editor = ace.edit('id_install_script_editor');
                anti_install_script_editor = ace.edit('id_anti_install_script_editor');
                stateguard_script_editor = ace.edit('id_stateguard_script_editor');
                start_script_editor = ace.edit('id_start_script_editor');
                stop_script_editor = ace.edit('id_stop_script_editor');
                state_script_editor = ace.edit('id_state_script_editor');
                extra_param_editor = ace.edit('id_extra_param_editor');
                initEditor(install_script_editor, 'id_install_script')
                initEditor(anti_install_script_editor, 'id_anti_install_script')
                initEditor(stateguard_script_editor, 'id_stateguard_script')
                initEditor(start_script_editor, 'id_start_script')
                initEditor(stop_script_editor, 'id_stop_script')
                initEditor(state_script_editor, 'id_state_script')
                initEditor(extra_param_editor, 'id_extra_param')
            }
        );
        function initEditor(editor, editorid) {
            editor.setTheme("ace/theme/xcode");
            editor.session.setMode("ace/mode/yaml");
            editor.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true
            });
            require(["ace/requirejs/text!src/ace"], function (e) {
                editor.setValue($('#' + editorid).val());
            })
        }
        require(['editor'])
    </script>

{% endblock %}

deploy_manager/templates/deploy_manager/project_version_form.html
{% extends 'common/basic_layout.html' %}

{% block content %}
    <script src="/static/asserts/require.js"></script>
    <link href="/static/hplus/css/plugins/chosen/chosen.css" rel="stylesheet">
    <script src="/static/hplus/js/plugins/chosen/chosen.jquery.js"></script>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>版本
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <form method="post" enctype="multipart/form-data"
                              onsubmit="return preSubmit()"
                              class="form-horizontal">
                            {% csrf_token %}
                            <input type="hidden" id="pid" name="pid" value="{{ pk }}"/>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.files.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.files }}
                                    {{ form.files.errors }}
                                    <div class="alert alert-success">
                                        SLS压缩包中的init将会被用作部署,start.sls被用于业务启动,stop.sls被用于业务暂停,uninstall.sls被用于业务卸载
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.software_files.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.software_files }}
                                    {{ form.software_files.errors }}
                                    <div class="alert alert-success">
                                        SLS中所使用的部署文件,使用方式为salt://....
                                    </div>
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-primary" type="submit">保存</button>
                                    <a class="btn btn-white" href="javascript:history.go(-1)">取消</a>
                                </div>
                            </div>
                        </form>
                        <hr/>
                        <table class="table table-striped table-bordered table-hover dataTables-example dataTable">
                            <thead>
                            <tr>
                                <th style="width: 7%;">版本</th>
                                <th style="width:5%;">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for project_version in project_versions %}
                                <tr>
                                    <th style="width: 7%;"><a
                                            href="/static/scripts/{{ project_version.files|file_path_filter }}"> {{ project_version.files|file_path_filter }}</a>
                                    </th>
                                    <th style="width:5%;">
                                        <a href="/frontend/deploy_manager/project_list/{{ project_version.id }}/project_version_edit/?pk={{ project_version.project.id }}"
                                           class="btn  btn-sm btn-info"><i class="fa fa-edit"></i>编辑</a>
                                        <a href="javascript:void(0)"
                                           onclick="removeVersion('{{ project_version.id }}',this)"
                                           class="btn  btn-sm btn-danger"><i class="fa fa-trash"></i>删除</a>
                                    </th>
                                </tr>
                            {% endfor %}
                            <script>
                                function removeVersion(id, content) {
                                    $.get('/frontend/deploy_manager/project_list/delete_project_version/?id=' + id, function (rs) {
                                        var obj = $($(content).parent()[0]).parent()[0]
                                        obj.remove()
                                    })
                                }
                            </script>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>


        $(document).ready(function () {
            var fieldObj = $('.form-horizontal input')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
            fieldObj = $('.form-horizontal textarea')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }

            fieldObj = $('.form-horizontal select')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
            $('#id_is_default').removeClass('form-control')
            $('#id_files').removeClass('form-control')
            $('#id_software_files').removeClass('form-control')

        })
    </script>

{% endblock %}