cmdb/urls.py
from django.conf.urls import include, url

from cmdb.views import *

urlpatterns = [
    # 机房等级

    url(r'^idc_level_list/', include([
        url(r'^delete_entity/', IDCLevelDeleteView.as_view(), name='idc_level_delete'),
        url(r'^(?P<pk>\d+)/idc_level_edit/', IDCLevelUpdateView.as_view(), name='idc_level_edit'),
        url(r'^idc_level_add/', IDCLevelCreateView.as_view(), name='idc_level_add'),
        url(r'^$', IDCLevelView.as_view(), name='idc_level_list'),
    ])),

    # ISP
    url(r'^isp_list/', include([
        url(r'^delete_entity/', ISPDeleteView.as_view(), name='isp_delete'),
        url(r'^(?P<pk>\d+)/isp_edit/', ISPUpdateView.as_view(), name='isp_edit'),
        url(r'^isp_add/', ISPCreateView.as_view(), name='isp_add'),
        url(r'^$', ISPView.as_view(), name='isp_list'),
    ])),

    # IDC
    url(r'^idc_list/', include([
        url(r'^delete_entity/', IDCDeleteView.as_view(), name='idc_delete'),
        url(r'^(?P<pk>\d+)/idc_edit/', IDCUpdateView.as_view(), name='idc_edit'),
        url(r'^idc_add/', IDCCreateView.as_view(), name='idc_add'),
        url(r'^$', IDCView.as_view(), name='idc_list'),
    ])),

    # 机柜
    url(r'^cabinet_list/', include([
        url(r'^delete_entity/', CabinetDeleteView.as_view(), name='cabinet_delete'),
        url(r'^(?P<pk>\d+)/cabinet_edit/', CabinetUpdateView.as_view(), name='cabinet_edit'),
        url(r'^cabinet_add/', CabinetCreateView.as_view(), name='cabinet_add'),
        url(r'^$', CabinetView.as_view(), name='cabinet_list'),
    ])),

    # 机架
    url('^rack_list/', include([
        url(r'^load_cabinet_list/', LoadCabinetListView.as_view()),
        url(r'^load_rack_list/', LoadRackListView.as_view()),
        url(r'^delete_entity/', RackDeleteView.as_view(), name='rack_delete'),
        url(r'^(?P<pk>\d+)/rack_edit/', RackUpdateView.as_view(), name='rack_edit'),
        url(r'^rack_add/', RackCreateView.as_view(), name='rack_add'),
        url(r'^$', RackView.as_view(), name='rack_list'),
    ])),

    # 主机组
    url('^hostgroup_list/', include([
        url(r'^delete_entity/', HostGroupDeleteView.as_view(), name='hostgroup_delete'),
        url(r'^(?P<pk>\d+)/hostgroup_edit/', HostGroupUpdateView.as_view(), name='hostgroup_edit'),
        url(r'^hostgroup_add/', HostGroupCreateView.as_view(), name='hostgroup_add'),
        url(r'^$', HostGroupView.as_view(), name='hostgroup_list'),
    ])),

    # 主机
    url('^host_list/', include([
        url(r'scan_host_job/', ScanHostJobView.as_view()),
        url(r'^delete_entity/', HostDeleteView.as_view(), name='host_delete'),
        url(r'^(?P<pk>\d+)/host_edit/', HostUpdateView.as_view(), name='host_edit'),
        url(r'^host_add/', HostCreateView.as_view(), name='host_add'),
        url(r'^host_export/', HostExportView, name='host_export'),
        url(r'^$', HostView.as_view(), name='host_list'),
    ])),

    # 资产导入
    url(r'assert_import/', include([
        url(r'upload_file/', AssertImportView.as_view()),
        url(r'^$', AssertImportCreateView.as_view(), name='assert_import'),
    ])),

]

saltops/urls.py
# -*- coding: utf-8 -*-
"""saltops URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions import serializers
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from rest_framework import routers

# from deploy_manager.serializer import UserViewSet
from common import views
from common.views import LoginView
from deploy_manager.views import *
from saltops import settings

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^app/', TemplateView.as_view(template_name="index.html")),
    url(r'^api/', include('base_auth.api_urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', LoginView.as_view(), name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^mainform/$', views.mainform, name='mainform'),
    url(r'^dashboard/$', views.dashboard, name='mainform'),
    url(r'^frontend/cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^frontend/tools_manager/', include('tools_manager.urls', namespace='tools_manager')),
    url(r'^frontend/deploy_manager/', include('deploy_manager.urls', namespace='deploy_manager')),
    url(r'^frontend/base_auth/', include('base_auth.urls', namespace='base_auth')),
    url(r'^frontend/celery_manager/', include('celery_manager.urls', namespace='celery_manager'))
]
#
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]
admin.site.site_header = 'SaltOps'
admin.site.site_title = 'SaltOps'

tools_manager/urls.py
from django.conf.urls import include, url

from tools_manager.views import *

urlpatterns = [
    # 工具类型
    url(r'^tools_types_list/', include([
        url(r'^delete_entity/', ToolsTypesDeleteView.as_view(), name='tools_types_delete'),
        url(r'^(?P<pk>\d+)/tools_types_edit/', ToolsTypesUpdateView.as_view(), name='tools_types_edit'),
        url(r'^tools_types_add/', ToolsTypesCreateView.as_view(), name='tools_types_add'),
        url(r'^$', ToolsTypesView.as_view(), name='tools_types_list'),
    ])),

    url(r'^tools_script_list/', include([
        url(r'^tool_execute_history/', ToolExecuteHistoryView.as_view()),
        url(r'^tool_execute_action/', ToolExecuteActionView.as_view()),
        url(r'^delete_entity/', ToolsScriptDeleteView.as_view(), name='tools_script_delete'),
        url(r'^^(?P<pk>\d+)/tools_script_edit/', ToolsScriptUpdateView.as_view(), name='tools_script_edit'),
        url(r'^tools_script_add/', ToolsScriptCreateView.as_view(), name='tools_script_add'),
        url(r'^tool_execute/', ToolExecuteView.as_view()),
        url(r'^$', ToolsScriptView.as_view(), name='tools_script_list'),
    ])),

]

tools_manager/models/ToolsExecDetailHistory.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel
from tools_manager.models.ToolsExecJob import ToolsExecJob


class ToolsExecDetailHistory(BaseModel):
    tool_exec_history = models.ForeignKey(ToolsExecJob, blank=True, null=True)
    host = models.ForeignKey(Host, verbose_name='目标主机', blank=True, null=True)
    exec_result = models.TextField(verbose_name='执行结果', blank=True, null=True, default="")
    err_msg = models.TextField(verbose_name='错误信息', blank=True, null=True, default="")

    def __str__(self):
        return self.host.host_name

    class Meta:
        verbose_name = "工具详细信息"
        verbose_name_plural = verbose_name

tools_manager/models/ToolsScript.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel
from tools_manager.models.ToolsTypes import ToolsTypes

TOOL_RUN_TYPE = (
    (0, 'SaltState'),
    (1, 'Shell'),
    (2, 'PowerShell'),
    (3, 'Python'),
    (4, 'Salt命令'),
    (5, 'Windows批处理')
)



class ToolsScript(BaseModel):
    name = models.CharField(max_length=255, verbose_name='工具名称')
    tool_script = models.TextField(verbose_name='脚本')
    tools_type = models.ForeignKey(ToolsTypes, verbose_name='工具类型')
    tool_run_type = models.IntegerField(verbose_name='脚本类型', choices=(TOOL_RUN_TYPE), default=0)
    comment = models.TextField(verbose_name='工具说明', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "工具"
        verbose_name_plural = verbose_name

tools_manager/models/ToolsTypes.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel


class ToolsTypes(BaseModel):
    name = models.CharField(max_length=255, verbose_name='类型名称')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "工具类型"
        verbose_name_plural = verbose_name

tools_manager/forms/ToolsScriptForm.py
from django import forms

from common.constants import FORM_WIDGET_BASE_STYLE
from tools_manager.models import *


class ToolsScriptForm(forms.ModelForm):
    class Meta:
        model = ToolsScript
        fields = '__all__'


# TODO:这里应该优化，从原有的脚本类型里面追加一条记录才合适
TOOL_RUN_TYPE_FILTER = (
    (None, '脚本类型'),
    (0, 'SaltState'),
    (1, 'Shell'),
    (2, 'PowerShell'),
    (3, 'Python'),
    (4, 'Salt命令'),
    (5, 'Windows批处理')
)


class ToolsScriptListFilterForm(forms.Form):
    tools_type = forms.ModelChoiceField(
        required=False,
        queryset=ToolsTypes.objects,
        empty_label='工具类型')
    name = forms.CharField(required=False, label='工具名称')
    tool_run_type = forms.ChoiceField(
        choices=TOOL_RUN_TYPE_FILTER,
        required=False)

tools_manager/forms/ToolsTypesForm.py
from django import forms

from tools_manager.models import *


class ToolsTypesForm(forms.ModelForm):
    class Meta:
        model = ToolsTypes
        fields = '__all__'

tools_manager/views.py
from django.shortcuts import render

# Create your views here.

tools_manager/views/tools_script.py
import re

import arrow
import yaml
from braces.views import *
from django.contrib.auth.mixins import *
from django.urls import *
from django.utils.safestring import mark_safe
from django.views.generic import *

from cmdb.models import HostGroup, Host
from common.pageutil import preparePage
from saltjob.tasks import execTools
from saltops.settings import PER_PAGE
from tools_manager.forms import *
from tools_manager.models import *

listview_lazy_url = 'tools_manager:tools_script_list'
listview_template = 'tools_manager/tools_script_list.html'
formview_template = 'tools_manager/tools_script_form.html'


class ToolsScriptView(LoginRequiredMixin,
                      OrderableListMixin,
                      ListView):
    model = ToolsScript
    orderable_columns_default = 'id'
    orderable_columns = ['name', 'tool_script', 'tools_type', 'tool_run_type', 'create_time', 'update_time']
    paginate_by = PER_PAGE
    template_name = listview_template
    context_object_name = 'result_list'

    def get_queryset(self):
        result_list = ToolsScript.objects.all()
        tools_type = self.request.GET.get('tools_type')
        name = self.request.GET.get('name')
        tool_run_type = self.request.GET.get('tool_run_type')
        order_by = self.request.GET.get('order_by')
        ordering = self.request.GET.get('ordering')
        if tools_type:
            result_list = result_list.filter(tools_type=tools_type)
        if name:
            result_list = result_list.filter(name__contains=name)
        if tool_run_type:
            result_list = result_list.filter(tool_run_type=tool_run_type)
        if order_by:
            if ordering == 'desc':
                result_list = result_list.order_by('-' + order_by)
            else:
                result_list = result_list.order_by(order_by)

        return result_list

    def get_context_data(self, **kwargs):
        context = super(ToolsScriptView, self).get_context_data(**kwargs)
        context['order_by'] = self.request.GET.get('order_by', '')
        context['ordering'] = self.request.GET.get('ordering', 'asc')
        context['filter_form'] = ToolsScriptListFilterForm(self.request.GET)
        return context


class ToolsScriptCreateView(LoginRequiredMixin, CreateView):
    model = ToolsScript
    form_class = ToolsScriptForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class ToolsScriptUpdateView(LoginRequiredMixin, UpdateView):
    model = ToolsScript
    form_class = ToolsScriptForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class ToolsScriptDeleteView(LoginRequiredMixin, JSONResponseMixin,
                            AjaxResponseMixin, View):
    def get_ajax(self, request, *args, **kwargs):
        ids = request.GET.get('id', '')
        if ids != "":
            ToolsScript.objects.filter(pk__in=map(int, ids.split(','))).delete()
            return self.render_json_response({"success": True})
        else:
            return self.render_json_response({"success": False})


class ToolExecuteHistoryView(ListView, LoginRequiredMixin):
    template_name = 'tools_manager/tool_script_execute_history.html'
    context_object_name = 'result_list'
    paginate_by = PER_PAGE

    def get_queryset(self):
        result_list = ToolsExecJob.objects.order_by('-create_time').filter(tools=self.request.GET.get('pk'))
        return result_list

    def get_context_data(self, **kwargs):
        context = super(ToolExecuteHistoryView, self).get_context_data(**kwargs)
        result = []
        for k in context['result_list']:
            host = ""
            for h in k.hosts.all():
                host += h.host_name + "<br/>"

            history = ToolsExecDetailHistory.objects.filter(tool_exec_history=k)
            result.append({
                "id": k.id,
                "hosts_count": k.hosts.count(),
                "create_time": k.create_time,
                "human_time": arrow.get(k.create_time).humanize(locale="zh"),
                "hosts": mark_safe(host),
                "result_hist": history,
                "success_count": len([x for x in history if x.err_msg == '']),
                "err_count": len([x for x in history if x.err_msg != ''])
            })
        context['result_list'] = result
        return context


class ToolExecuteView(TemplateView, LoginRequiredMixin):
    template_name = 'tools_manager/tool_script_execute_form.html'

    def get_context_data(self, **kwargs):
        context = super(ToolExecuteView, self).get_context_data(**kwargs)
        pk = self.request.GET.get('pk', '')
        if pk:
            context['hostgroup'] = HostGroup.objects.all()

            context['hosts'] = Host.objects.all()
            pk = int(pk)
            entity = ToolsScript.objects.get(pk=pk)
            context['pk'] = pk
            context['entity'] = entity
            params = re.findall('\${(.*?)}', entity.tool_script)
            param_list = []
            for obj in params:
                if len(obj.split(':')) == 2:
                    param_dict = (obj.split(':')[0], obj.split(':')[1])
                    param_list.append(param_dict)
            context['param_list'] = param_list
        return context


class ToolExecuteActionView(LoginRequiredMixin, JSONResponseMixin,
                            AjaxResponseMixin, View):
    def post_ajax(self, request, *args, **kwargs):
        hostids = request.POST['hostids']
        hostgroup_ids = request.POST['hostgroup_ids']
        obj = ToolsScript.objects.get(pk=int(request.POST.get('id')))
        params = re.findall('\${(.+?)}', obj.tool_script)
        param_obj = {}
        for entity in params:
            if ':' in entity:
                param_obj[entity.split(':')[1]] = request.POST[entity.split(':')[1]]
        if param_obj != "":
            yaml_str = yaml.dump(param_obj)
        hostlist = []
        if hostids != "":
            hostlist.extend(hostids.split(','))

        if hostgroup_ids != "":
            hosts = Host.objects.filter(host_group_id__in=hostgroup_ids.split(','))
            for k in hosts:
                hostlist.append(k.id)
        hostlist = list(set(hostlist))
        toolExecJob, exec_detail_list = execTools(obj, hostlist, yaml_str)
        # 把结果返回给前端展示
        result = []
        for k in exec_detail_list:
            result.append({
                'exec_result': k.exec_result,
                'err_msg': k.err_msg,
                'host': k.host.host_name,
            })
        return self.render_json_response(result)

tools_manager/views/tools_types.py
from braces.views import *
from django.contrib.auth.mixins import *
from django.urls import *
from django.views.generic import *

from saltops.settings import PER_PAGE
from tools_manager.forms import *
from tools_manager.models import *

listview_lazy_url = 'tools_manager:tools_types_list'
listview_template = 'tools_manager/tools_types_list.html'
formview_template = 'tools_manager/tools_types_form.html'


class ToolsTypesView(LoginRequiredMixin,
                     OrderableListMixin,
                     ListView):
    model = ToolsTypes
    paginate_by = PER_PAGE
    orderable_columns_default = 'id'
    orderable_columns = ['name']
    template_name = listview_template
    context_object_name = 'result_list'


class ToolsTypesCreateView(LoginRequiredMixin, CreateView):
    model = ToolsTypes
    form_class = ToolsTypesForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class ToolsTypesUpdateView(LoginRequiredMixin, UpdateView):
    model = ToolsTypes
    form_class = ToolsTypesForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class ToolsTypesDeleteView(LoginRequiredMixin, JSONResponseMixin,
                           AjaxResponseMixin, View):
    def get_ajax(self, request, *args, **kwargs):
        ids = request.GET.get('id', '')
        if ids != "":
            ToolsTypes.objects.filter(pk__in=map(int, ids.split(','))).delete()
            return self.render_json_response({"success": True})
        else:
            return self.render_json_response({"success": False})

tools_manager/templates/tools_manager/tool_script_execute_history.html
{% extends 'common/basic_layout.html' %}

{% block content %}
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>执行记录</h5>
                <a class=" pull-right" href="javascript:history.go(-1)">返回</a>
            </div>

            <div class="ibox-content timeline">
                {% for o in result_list %}
                    <div class="timeline-item">
                        <div class="row">
                            <div class="col-xs-4 date">
                                <i class="fa fa-briefcase"></i> {{ o.create_time }}
                                <br>
                                <small class="text-navy">{{ o.human_time }}</small>
                            </div>
                            <div class="col-xs-7 content no-top-border">
                                <p class="m-b-xs"><strong>主机数量:{{ o.hosts_count }}</strong>
                                    执行成功:{{ o.success_count }}
                                    执行失败:{{ o.err_count }}
                                </p>
                                <p>{{ o.hosts }}</p>
                                <a href="javascript:void(0)" onclick="showHistory('{{ o.id }}')">详细信息</a>
                                <div id="{{ o.id }}" style="display: none">
                                    {% for v in o.result_hist %}
                                        <p>{{ v.host }}</p>
                                        <hr/>
                                        <p>
                                            {{ v.exec_result|replace_to_br }}
                                        </p>
                                        <hr/>
                                        <p>
                                            {{ v.err_msg|replace_to_br }}
                                        </p>
                                    {% endfor %}

                                </div>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="hr-line-dashed"></div>
            {% include 'common/pagination.html' %}
        </div>
    </div>
    <script>
        function showHistory(id) {
            $('#' + id).toggle()
        }
    </script>
{% endblock %}

tools_manager/templates/tools_manager/tools_script_form.html
{% extends 'common/basic_layout.html' %}

{% block content %}
    <script src="/static/asserts/require.js"></script>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>{{ title }}
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <form method="post" action="{{ action }}" onsubmit="return preSubmit()" class="form-horizontal">
                            {% csrf_token %}
                            <input type="hidden" id="id" name="id" value="{{ pk }}"/>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.name.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.name }}
                                    {{ form.name.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.tool_script.label_tag }}</label>
                                <div class="col-sm-10" style="height: 200px" name="tool_script_editor"
                                     id="id_tool_script_editor"></div>
                                <textarea id="id_tool_script" name="tool_script"
                                          style="display: none">{{ form.tool_script.value|default_if_none:"" }}</textarea>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.tools_type.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.tools_type }}
                                    {{ form.tools_type.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.tool_run_type.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.tool_run_type }}
                                    {{ form.tool_run_type.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.comment.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.comment }}
                                    {{ form.comment.errors }}
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-primary" type="submit">保存</button>
                                    <a class="btn btn-white" href="javascript:history.go(-1)">取消</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var editor;
        function preSubmit() {
            $('#id_tool_script').val(editor.getValue())
            return true;
        }
        $(document).ready(function () {
            var fieldObj = $('.form-horizontal input')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
            fieldObj = $('.form-horizontal textarea')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }

            fieldObj = $('.form-horizontal select')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
        })

        require.config({paths: {ace: "/static/asserts/ace/lib/ace"}})


        define('editor', ['ace/ace'],
            function (ace, langtools) {
                {#                console.log("This is the testace module");#}
                editor = ace.edit("id_tool_script_editor");
                editor.setTheme("ace/theme/xcode");
                editor.session.setMode("ace/mode/yaml");
                editor.setOptions({
                    enableBasicAutocompletion: true,
                    enableSnippets: true,
                    enableLiveAutocompletion: true
                });
                require(["ace/requirejs/text!src/ace"], function (e) {
                    editor.setValue($('#id_tool_script').val());
                })
            }
        );
        require(['editor'])

        $('#id_tool_run_type').change(function (e) {
            if ($('#id_tool_run_type').val() == "0") {
                editor.session.setMode("ace/mode/yaml");
            }
            if ($('#id_tool_run_type').val() == "1") {
                editor.session.setMode("ace/mode/sh");
            }
            if ($('#id_tool_run_type').val() == "2") {
                editor.session.setMode("ace/mode/powershell");
            }
            if ($('#id_tool_run_type').val() == "3") {
                editor.session.setMode("ace/mode/python");
            }
            if ($('#id_tool_run_type').val() == "4") {
                editor.session.setMode("ace/mode/plain_text");
            }
            if ($('#id_tool_run_type').val() == "5") {
                editor.session.setMode("ace/mode/plain_text");
            }
        })
    </script>

{% endblock %}

tools_manager/templates/tools_manager/tools_script_list.html
{% extends 'common/basic_list.html' %}
{% block list_title %}
    工具
{% endblock %}

{% block list_filter %}
    <div class="col-sm-4">
        <div class="input-group">
            &nbsp;
            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> 搜索</button>
            &nbsp;
            <a href="tools_script_add/"
               class="btn btn-sm btn-success"><i class="fa fa-plus"></i> 新增</a>
            &nbsp;
            <a href="javascript:void(0)"
               onclick="deleteBatch()"
               class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> 批量删除</a>
        </div>
    </div>
{% endblock %}

{% block list_content %}
    <table class="table table-striped table-bordered table-hover dataTables-example dataTable">
        <thead>
        <tr>
            <th style="width: 2%;"><input id="checkall" type="checkbox" class="i-checks"></th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="tools_type" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>工具类型
                </a>
            </th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="name" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>名称
                </a>
            </th>
            <th style="width: 7%;">
                <a class="order-by-column" data-column="tool_run_type" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    脚本类型
                </a>
            </th>
            <th style="width: 20%;">
                <a class="order-by-column" data-column="comment" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    工具说明
                </a>
            </th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="create_time" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    创建时间
                </a>
            </th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="update_time" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    更新时间
                </a>
            </th>
            <th style="width:25%;">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for o in result_list %}
            <tr>
                <td>
                    <input type="checkbox" class="i-checks icheck" id="{{ o.id }}" name="input[]">
                </td>
                <td>{{ o.tools_type }}</td>
                <td>{{ o.name }}</td>
                <td>{{ o.tool_run_type|tools_type_filter }}</td>
                <td>{{ o.comment }}</td>
                <td>{{ o.create_time }}</td>
                <td>{{ o.update_time }}</td>
                <td>

                    <a href="{{ o.id }}/tools_script_edit/"
                       class="btn  btn-sm btn-info"><i class="fa fa-edit"></i>编辑</a>
                    <a href="tool_execute/?pk={{ o.id }}"
                       class="btn  btn-sm btn-primary"><i class="fa fa-play"></i>执行</a>
                    <a href="tool_execute_history/?pk={{ o.id }}"
                       class="btn  btn-sm btn-success"><i class="fa fa-expand"></i>历史</a>
                    <a href="javascript:void(0)"
                       onclick="deleteAction('{{ o.id }}')"
                       class="btn  btn-sm btn-danger"><i class="fa fa-trash"></i>删除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

tools_manager/templates/tools_manager/tools_types_form.html
{% extends 'common/basic_form.html' %}
{% block titleblock %}
    工具类型
{% endblock %}