cmdb/urls.py
from django.conf.urls import include, url

from cmdb.views import *

urlpatterns = [
    # 机房等级

    url(r'^idc_level_list/', include([
        url(r'^delete_entity/', IDCLevelDeleteView.as_view(), name='idc_level_delete'),
        url(r'^(?P<pk>\d+)/idc_level_edit/', IDCLevelUpdateView.as_view(), name='idc_level_edit'),
        url(r'^idc_level_add/', IDCLevelCreateView.as_view(), name='idc_level_add'),
        url(r'^$', IDCLevelView.as_view(), name='idc_level_list'),
    ])),

    # ISP
    url(r'^isp_list/', include([
        url(r'^delete_entity/', ISPDeleteView.as_view(), name='isp_delete'),
        url(r'^(?P<pk>\d+)/isp_edit/', ISPUpdateView.as_view(), name='isp_edit'),
        url(r'^isp_add/', ISPCreateView.as_view(), name='isp_add'),
        url(r'^$', ISPView.as_view(), name='isp_list'),
    ])),

    # IDC
    url(r'^idc_list/', include([
        url(r'^delete_entity/', IDCDeleteView.as_view(), name='idc_delete'),
        url(r'^(?P<pk>\d+)/idc_edit/', IDCUpdateView.as_view(), name='idc_edit'),
        url(r'^idc_add/', IDCCreateView.as_view(), name='idc_add'),
        url(r'^$', IDCView.as_view(), name='idc_list'),
    ])),

    # 机柜
    url(r'^cabinet_list/', include([
        url(r'^delete_entity/', CabinetDeleteView.as_view(), name='cabinet_delete'),
        url(r'^(?P<pk>\d+)/cabinet_edit/', CabinetUpdateView.as_view(), name='cabinet_edit'),
        url(r'^cabinet_add/', CabinetCreateView.as_view(), name='cabinet_add'),
        url(r'^$', CabinetView.as_view(), name='cabinet_list'),
    ])),

    # 机架
    url('^rack_list/', include([
        url(r'^load_cabinet_list/', LoadCabinetListView.as_view()),
        url(r'^load_rack_list/', LoadRackListView.as_view()),
        url(r'^delete_entity/', RackDeleteView.as_view(), name='rack_delete'),
        url(r'^(?P<pk>\d+)/rack_edit/', RackUpdateView.as_view(), name='rack_edit'),
        url(r'^rack_add/', RackCreateView.as_view(), name='rack_add'),
        url(r'^$', RackView.as_view(), name='rack_list'),
    ])),

    # 主机组
    url('^hostgroup_list/', include([
        url(r'^delete_entity/', HostGroupDeleteView.as_view(), name='hostgroup_delete'),
        url(r'^(?P<pk>\d+)/hostgroup_edit/', HostGroupUpdateView.as_view(), name='hostgroup_edit'),
        url(r'^hostgroup_add/', HostGroupCreateView.as_view(), name='hostgroup_add'),
        url(r'^$', HostGroupView.as_view(), name='hostgroup_list'),
    ])),

    # 主机
    url('^host_list/', include([
        url(r'scan_host_job/', ScanHostJobView.as_view()),
        url(r'^delete_entity/', HostDeleteView.as_view(), name='host_delete'),
        url(r'^(?P<pk>\d+)/host_edit/', HostUpdateView.as_view(), name='host_edit'),
        url(r'^host_add/', HostCreateView.as_view(), name='host_add'),
        url(r'^host_export/', HostExportView, name='host_export'),
        url(r'^$', HostView.as_view(), name='host_list'),
    ])),

    # 资产导入
    url(r'assert_import/', include([
        url(r'upload_file/', AssertImportView.as_view()),
        url(r'^$', AssertImportCreateView.as_view(), name='assert_import'),
    ])),

]

saltops/urls.py
# -*- coding: utf-8 -*-
"""saltops URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions import serializers
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from rest_framework import routers

# from deploy_manager.serializer import UserViewSet
from common import views
from common.views import LoginView
from deploy_manager.views import *
from saltops import settings

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^app/', TemplateView.as_view(template_name="index.html")),
    url(r'^api/', include('base_auth.api_urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', LoginView.as_view(), name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^mainform/$', views.mainform, name='mainform'),
    url(r'^dashboard/$', views.dashboard, name='mainform'),
    url(r'^frontend/cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^frontend/tools_manager/', include('tools_manager.urls', namespace='tools_manager')),
    url(r'^frontend/deploy_manager/', include('deploy_manager.urls', namespace='deploy_manager')),
    url(r'^frontend/base_auth/', include('base_auth.urls', namespace='base_auth')),
    url(r'^frontend/celery_manager/', include('celery_manager.urls', namespace='celery_manager'))
]
#
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]
admin.site.site_header = 'SaltOps'
admin.site.site_title = 'SaltOps'

cmdb/models/Host.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey

from cmdb.models.HostGroup import HostGroup
from cmdb.models.Cabinet import Cabinet
from cmdb.models.IDC import IDC
from cmdb.models.Rack import Rack
from common.models import BaseModel

MINION_STATUS = (
    (0, '未启动'),
    (1, '运行中'),
    (2, '待接受'),
    (3, '已拒绝'),
    (4, '已禁止'),
)


class Host(BaseModel):
    host_group = models.ForeignKey(HostGroup, verbose_name='主机组', blank=True, null=True)
    host_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="主机DNS名称")
    kernel = models.CharField(max_length=255, blank=True, null=True, verbose_name="系统内核")
    kernel_release = models.CharField(max_length=255, blank=True, null=True, verbose_name="系统内核版本")
    virtual = models.CharField(max_length=255, blank=True, null=True, verbose_name="设备类型")
    host = models.CharField(max_length=255, blank=True, null=True, verbose_name="主机名")
    osrelease = models.CharField(max_length=255, blank=True, null=True, verbose_name="操作系统版本")
    saltversion = models.CharField(max_length=255, blank=True, null=True, verbose_name="Salt版本")
    osfinger = models.CharField(max_length=255, blank=True, null=True, verbose_name="系统指纹")
    os_family = models.CharField(max_length=255, blank=True, null=True, verbose_name="系统类型")
    num_gpus = models.IntegerField(blank=True, null=True, verbose_name="GPU数量")
    system_serialnumber = models.CharField(max_length=255, blank=True, null=True, verbose_name="SN号")
    cpu_model = models.CharField(max_length=255, blank=True, null=True, verbose_name="CPU型号")
    productname = models.CharField(max_length=255, blank=True, null=True, verbose_name="产品名称")
    osarch = models.CharField(max_length=255, blank=True, null=True, verbose_name="系统架构")
    cpuarch = models.CharField(max_length=255, blank=True, null=True, verbose_name="CPU架构")
    os = models.CharField(max_length=255, blank=True, null=True, verbose_name="操作系统")
    mem_total = models.IntegerField(blank=True, null=True, verbose_name="内存大小")
    num_cpus = models.IntegerField(blank=True, null=True, verbose_name="CPU数量")
    idc = models.ForeignKey(IDC, verbose_name='IDC', blank=True, null=True)

    cabinet = models.ForeignKey(
        Cabinet,
        verbose_name="机柜",
        blank=True, null=True
    )
    rack = models.ForeignKey(
        Rack,
        verbose_name="机架",
        blank=True, null=True
    )
    minion_status = models.IntegerField(verbose_name='Minion状态', default=0,
                                        choices=MINION_STATUS)
    enable_ssh = models.BooleanField(verbose_name='使用Salt-SSH', choices=((True, '启用'), (False, '禁用')), default=False)
    ssh_username = models.CharField(verbose_name='SSH用户名', max_length=255, blank=True, null=True, default="")
    ssh_password = models.CharField(verbose_name='SSH密码', max_length=255, blank=True, null=True, default="")
    enable_sudo = models.BooleanField(verbose_name='启用Sudo', choices=((True, '启用'), (False, '禁用')), default=False)
    enable_tty = models.BooleanField(verbose_name='启用TTY', choices=((True, '启用'), (False, '禁用')), default=False)

    def __str__(self):
        return self.host_name

    class Meta:
        verbose_name = "主机"
        verbose_name_plural = verbose_name

cmdb/forms/CabinetForm.py
from django import forms

from cmdb.models import *
from common.constants import FORM_WIDGET_BASE_STYLE


class CabinetForm(forms.ModelForm):
    class Meta:
        model = Cabinet
        fields = ['idc', 'name']


class CabinetListFilterForm(forms.Form):
    idc = forms.ModelChoiceField(
        queryset=IDC.objects, required=False, empty_label='机房类型')
    name = forms.CharField(required=False, label='机柜')

cmdb/forms/HostForm.py
from django import forms

from cmdb.models import *
from common.constants import FORM_WIDGET_BASE_STYLE


class HostForm(forms.ModelForm):
    class Meta:
        model = Host
        fields = '__all__'


class HostListFilterForm(forms.Form):
    ip_filter = forms.CharField(
        required=False, label='IP')
    host_group = forms.ModelChoiceField(
        queryset=HostGroup.objects,
        empty_label='主机组', required=False)
    host = forms.CharField(required=False, label='主机名')

cmdb/views.py
from django.shortcuts import render

cmdb/views/assert_import.py
import logging
import traceback

import requests
import xlrd
from braces.views import *
from django.contrib.auth.mixins import *
from django.urls import *
from django.views.generic import *

from cmdb.forms import *
from cmdb.models import *
from saltops.settings import PER_PAGE, DEFAULT_LOGGER
from saltops.settings_backup import SALT_CONN_TYPE


class AssertImportCreateView(LoginRequiredMixin, TemplateView):
    template_name = 'cmdb/assert_import_index.html'


class AssertImportView(LoginRequiredMixin, JSONResponseMixin,
                       AjaxResponseMixin, View):
    def post_ajax(self, request, *args, **kwargs):
        logger = logging.getLogger(DEFAULT_LOGGER)

        assert_file = request.FILES.get("file", None)
        wb = xlrd.open_workbook(filename=None, file_contents=assert_file.read())
        # 读取机房等级信息
        idc_level_table = wb.sheets()[0]
        for i in range(1, idc_level_table.nrows):
            row = idc_level_table.row_values(i)
            if len(IDCLevel.objects.filter(name=row[0])) == 0:
                IDCLevel(name=row[0], comment=row[1]).save()

        # 读取ISP信息
        isp_table = wb.sheets()[1]
        for i in range(1, isp_table.nrows):
            row = isp_table.row_values(i)
            if len(ISP.objects.filter(name=row[0])) == 0:
                ISP(name=row[0]).save()

        # 读取机房信息
        idc_table = wb.sheets()[2]
        for i in range(1, idc_table.nrows):
            row = idc_table.row_values(i)
            if len(IDC.objects.filter(name=row[0])) == 0:
                try:
                    IDC(name=row[0], bandwidth=row[1],
                        phone=row[2], linkman=row[3],
                        address=row[4], concat_email=row[5],
                        network=row[6], operator=ISP.objects.get(name=row[7]),
                        type=IDCLevel.objects.get(name=row[8]), comment=row[9]).save()
                except Exception as e:
                    pass

        # 机柜
        for i in range(1, wb.sheets()[3].nrows):
            row = wb.sheets()[3].row_values(i)
            if len(Cabinet.objects.filter(name=row[1])) == 0:
                try:
                    Cabinet(idc=IDC.objects.get(name=row[0]), name=row[1]).save()
                except Exception as e:
                    pass

        # 机架
        for i in range(1, wb.sheets()[4].nrows):
            row = wb.sheets()[4].row_values(i)
            if len(Rack.objects.filter(name=row[1])) == 0:
                try:
                    Rack(idc=IDC.objects.get(name=row[0]),
                         cabinet=Cabinet.objects.get(name=row[1]),
                         name=row[2]).save()
                except Exception as e:
                    pass

        # 主机组
        for i in range(1, wb.sheets()[5].nrows):
            row = wb.sheets()[5].row_values(i)
            if len(HostGroup.objects.filter(name=row[1])) != 0:
                continue
            try:
                if row[0] == "":
                    HostGroup(name=row[1]).save()
                else:
                    HostGroup(parent=HostGroup.objects.get(name=row[0]), name=row[1]).save()
            except Exception as e:
                pass

        # 主机
        for i in range(1, wb.sheets()[6].nrows):
            row = wb.sheets()[6].row_values(i)
            enable_sudo = False
            enable_ssh = False

            excel_enable_sudo = row[9] if type(row[9]) != float else str(int(row[9]))
            excel_enable_ssh = row[6] if type(row[6]) != float else str(int(row[6]))
            try:
                if excel_enable_sudo != '0':
                    enable_sudo = True
                if excel_enable_ssh != '0':
                    enable_ssh = True
            except Exception as e:
                pass
            if len(Host.objects.filter(host_name=row[1])) != 0:
                continue
            if row[1] != '' and Host.objects.filter(host=row[1]).count() == 0:
                try:
                    excel_host_name = row[1] if type(row[1]) != float else str(int(row[1]))
                    excel_host = row[2] if type(row[2]) != float else str(int(row[2]))
                    excel_username = row[7] if type(row[7]) != float else str(int(row[7]))
                    excel_password = row[8] if type(row[8]) != float else str(int(row[8]))
                    host = Host(
                        host_name=excel_host_name,
                        host=excel_host,
                        enable_ssh=enable_ssh,
                        ssh_username=excel_username,
                        ssh_password=excel_password,
                        enable_sudo=enable_sudo)
                    if str(row[0]) != '' and HostGroup.objects.filter(name=str(row[0])).count() != 0:
                        host.host_group = HostGroup.objects.get(name=str(row[0]))
                    if str(row[3]) != '' and IDC.objects.filter(name=str(row[3])).count() != 0:
                        host.idc = IDC.objects.get(name=str(row[3]))
                    if str(row[4]) != '' and Cabinet.objects.filter(name=str(row[4])).count() != 0:
                        host.cabinet = Cabinet.objects.get(name=str(row[4]))
                    if str(row[5]) != '' and Rack.objects.filter(name=str(row[5])).count() != 0:
                        host.rack = Rack.objects.get(name=str(row[5]))
                    host.save()

                except Exception as e:
                    logger.error('导入主机失败[%s]' % traceback.format_exc())

            # 更新一遍Rouster信息
            hosts = Host.objects.all()

            rosterString = ""
            for host in hosts:
                if host.enable_ssh is True:
                    rosterString += """

                %s:
                    host: %s
                    user: %s
                    passwd: %s
                    sudo: %s
                    tty: True

                                """ % (host.host, host.host, host.ssh_username, host.ssh_password,
                                       host.enable_ssh)

            if SALT_CONN_TYPE == 'http':
                requests.post(SALT_HTTP_URL + '/rouster', data={'content': rosterString})
            else:
                try:
                    with open('/etc/salt/roster', 'w') as content:
                        content.write(rosterString)
                except Exception as e:
                    logger.error("写入SaltSSH文件失败，无权限或无该文件")
        return self.render_json_response({})

cmdb/views/host_group.py
from braces.views import *
from django.contrib.auth.mixins import *
from django.urls import *
from django.views.generic import *

from cmdb.forms import *
from cmdb.models import *
from saltops.settings import PER_PAGE

listview_lazy_url = 'cmdb:hostgroup_list'
listview_template = 'cmdb/hostgroup_list.html'
formview_template = 'cmdb/hostgroup_form.html'


class HostGroupView(LoginRequiredMixin, OrderableListMixin, ListView):
    model = HostGroup
    paginate_by = PER_PAGE
    template_name = listview_template
    context_object_name = 'result_list'
    orderable_columns_default = 'id'
    orderable_columns = ['host_group', 'host_name', 'create_time', 'update_time']


class HostGroupCreateView(LoginRequiredMixin, CreateView):
    model = HostGroup
    form_class = HostGroupForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class HostGroupUpdateView(LoginRequiredMixin, UpdateView):
    model = HostGroup
    form_class = HostGroupForm
    template_name = formview_template
    success_url = reverse_lazy(listview_lazy_url)


class HostGroupDeleteView(LoginRequiredMixin, JSONResponseMixin,
                          AjaxResponseMixin, View):
    def get_ajax(self, request, *args, **kwargs):
        ids = request.GET.get('id', '')
        if ids != "":
            HostGroup.objects.filter(pk__in=map(int, ids.split(','))).delete()
            return self.render_json_response({"success": True})
        else:
            return self.render_json_response({"success": False})

cmdb/templates/cmdb/assert_import_index.html
{% extends 'common/basic_layout.html' %}
{% block content %}
    <link href="/static/hplus/css/plugins/dropzone/basic.css" rel="stylesheet">
    <link href="/static/hplus/css/plugins/dropzone/dropzone.css" rel="stylesheet">
    <script src="/static/hplus/js/content.min.js?v=1.0.0"></script>
    <script src="/static/hplus/js/plugins/dropzone/dropzone.js"></script>
    <link href="/static/hplus/css/plugins/toastr/toastr.min.css" rel="stylesheet">
    <script src="/static/hplus/js/plugins/toastr/toastr.min.js"></script>
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>资产导入</h5>
            </div>
            <div class="ibox-content">
                <form id="my-awesome-dropzone" class="dropzone" method="post"
                      action="upload_file/">
                    {% csrf_token %}
                    <div class="dropzone-previews"></div>
                </form>
                <div>
                    <div class="m">
                        使用资产导入功能可以实现对资产进行本地快速导入，点击链接：
                        <a href="/static/asserts/资产模板.xlsx" target="_blank">下载导入模板</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "progressBar": true,
            "positionClass": "toast-top-full-width",
            "onclick": null,
            "showDuration": "400",
            "hideDuration": "1000",
            "timeOut": "7000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        $(".dropzone").dropzone({
            init: function () {
                this.on("complete", function (file) {
                    toastr.success("资产导入", "资产导入成功")
                })
            }
        });
    </script>
{% endblock %}

cmdb/templates/cmdb/cabinet_form.html
{% extends 'common/basic_form.html' %}
{% block titleblock %}
    机柜
{% endblock %}

cmdb/templates/cmdb/cabinet_list.html
{% extends 'common/basic_list.html' %}

{% block list_title %}
    机柜
{% endblock %}

{% block list_filter %}
    <div class="col-sm-4">
        <div class="input-group">
            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> 搜索</button>
            &nbsp;
            <a href="cabinet_add/"
               class="btn btn-sm btn-success"><i class="fa fa-plus"></i> 新增</a>
            &nbsp;
            <a href="javascript:void(0)"
               onclick="deleteBatch()"
               class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> 批量删除</a>
        </div>
    </div>
{% endblock %}

{% block list_content %}
    <table class="table table-striped table-bordered table-hover dataTables-example dataTable">
        <thead>
        <tr>
            <th><input id="checkall" type="checkbox" class="i-checks"></th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="idc" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    机房
                </a>
            </th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="name" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    机柜
                </a>
            </th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="create_time" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    创建时间
                </a>
            </th>
            <th style="width: 10%;">
                <a class="order-by-column" data-column="update_time" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    更新时间
                </a>
            </th>
            <th style="width:10%;">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for o in result_list %}
            <tr>
                <td style="width: 3%;">
                    <input type="checkbox" class="i-checks icheck" id="{{ o.id }}" name="input[]">
                </td>
                <td>{{ o.idc }}</td>
                <td>{{ o.name }}</td>
                <td>{{ o.create_time }}</td>
                <td>{{ o.update_time }}</td>
                <td>
                    <a href="{{ o.id }}/cabinet_edit/"
                       class="btn  btn-sm btn-info"><i class="fa fa-edit"></i>编辑</a>
                    <a href="javascript:void(0)"
                       onclick="deleteAction('{{ o.id }}')"
                       class="btn  btn-sm btn-danger"><i class="fa fa-trash"></i>删除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

cmdb/templates/cmdb/host_list.html
{% extends 'common/basic_list.html' %}

{% block list_title %}
    主机
{% endblock %}

{% block list_filter %}
    <div class="col-sm-6">
        <div class="input-group">
            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> 搜索</button>
            &nbsp;
            <a href="host_add/"
               class="btn btn-sm btn-success"> 新增</a>&nbsp;
            <a href="javascript:void(0)"
               onclick="scan_host()"
               class="btn btn-sm btn-success"> 扫描主机</a>
            &nbsp;
            <a href="javascript:void(0)"
               onclick="exportCsv()"
               class="btn btn-sm btn-success"> 导出列表</a>&nbsp;
            &nbsp;
            <a href="javascript:void(0)"
               onclick="deleteBatch()"
               class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> 批量删除</a>
        </div>
    </div>
    <script>
        function exportCsv() {
            layer.load();
            let url = '/frontend/cmdb/host_list/host_export/?host=' +
                $('#id_host').val() + "&ip_filter=" + $('#id_ip_filter').val()
                + "&host_group=" + $('#id_host_group').val();
            window.location.href = url
            layer.closeAll('loading');
        }

        function scan_host() {
            layer.load();
            $.get('/frontend/cmdb/host_list/scan_host_job/', function () {
                location.reload()
                layer.closeAll('loading');
            })

        }
    </script>
{% endblock %}

{% block list_content %}
    <div class="ibox " style="display: none;" id="loading_div">
        <div class="spiner-example">
            <div class="sk-spinner sk-spinner-three-bounce">
                <div class="sk-bounce1"></div>
                <div class="sk-bounce2"></div>
                <div class="sk-bounce3"></div>
            </div>
        </div>
    </div>
    <table id="tb" class="table table-striped table-bordered table-hover dataTables-example dataTable">
        <thead>
        <tr>
            <th style="width:3%;"><input id="checkall" type="checkbox" class="i-checks"></th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="host_group" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    主机组
                </a>
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="host_name" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    主机DNS名称
                </a>
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="host" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    主机名
                </a>
            </th>
            <th style="width: 8%;">
                IP
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="idc" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    机房
                </a>
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="os" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    系统内核
                </a>
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="enable_ssh" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    使用SaltSSH
                </a>
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="minion_status" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    Minion状态
                </a>
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="create_time" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    创建时间
                </a>
            </th>
            <th style="width: 8%;">
                <a class="order-by-column" data-column="update_time" href="#">
                    <i class="fa fa-sort order-by-column_icon"></i>
                    更新时间
                </a>
            </th>
            <th style="width:15%;">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for o in result_list %}
            <tr>
                <td>
                    <input type="checkbox" class="i-checks icheck" id="{{ o.id }}" name="input[]">
                </td>
                <td>{% ifequal o.host_group None %}
                    无
                {% else %}
                    {{ o.host_group }}
                {% endifequal %}
                </td>
                <td>{{ o.host_name }}</td>
                <td>{{ o.host }}</td>
                <td>{{ o.id|host_ip_filter }}</td>
                <td>{% ifequal o.idc None %}
                    无
                {% else %}
                    {{ o.idc }}
                {% endifequal %}</td>
                <td>{{ o.os }}</td>
                <td>{{ o.enable_ssh|enablessh_status_filter }}</td>
                <td>{{ o.minion_status|minion_status_filter }}</td>
                <td>{{ o.create_time }}</td>
                <td>{{ o.update_time }}</td>
                <td>
                    <a href="/frontend/cmdb/host_list/{{ o.id }}/host_edit/"
                       class="btn  btn-sm btn-info"><i class="fa fa-edit"></i>编辑</a>
                    <a href="javascript:void(0)"
                       onclick="deleteAction('{{ o.id }}')"
                       class="btn  btn-sm btn-danger"><i class="fa fa-trash"></i>删除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

cmdb/templates/cmdb/hostgroup_form.html
{% extends 'common/basic_form.html' %}
{% block titleblock %}
    主机组
{% endblock %}

cmdb/templates/cmdb/idc_form.html
{% extends 'common/basic_form.html' %}
{% block titleblock %}
    机房
{% endblock %}

cmdb/templates/cmdb/idc_level_form.html
{% extends 'common/basic_form.html' %}
{% block titleblock %}
    机房等级
{% endblock %}

cmdb/templates/cmdb/isp_form.html
{% extends 'common/basic_form.html' %}
{% block titleblock %}
    ISP
{% endblock %}